### ISSUE TITLE
Kailh Choc switches

### ISSUE THREAD

**Issue by hanslenze** [camrbuss/pinci#2]
Since Kailh Choc Mini switches (PG1232) are so hard to get. Can you make a version that uses "normal" low profile Kailh Choc switches (PG1350)?

**Comment by camrbuss** [comment]
It looks like you can still buy the PG1232 on Kailh's aliexpress store. https://www.aliexpress.com/item/32989908397.html?spm=a2g0o.9042311.0.0.40af4c4djiMwT9

If you really want the PG1350, you could definitely just change the footprint and then just update the board. Should be pretty easy.

**Comment by hanslenze** [comment]
Thank you so much for that link! I'll make a Choc Mini version when they get to my doorstep.
