### ISSUE TITLE
Any possibility of a 36-key variation?

### ISSUE THREAD

**Issue by theroncross** [camrbuss/pinci#3]

**Comment by camrbuss** [comment]
It would significantly change the board outline, so it would be a decent amount of work. If you had the coordinates of where you wanted the extra-key it would be possible, but also would likely need a re-route. Are you interested in working on it or asking if I will do it?

**Comment by theroncross** [comment]
I would be starting from zero knowledge, so would be unlikely to make much progress soon. You can close this.
