### ISSUE TITLE
Are there any build guide?

### ISSUE THREAD

**Issue by KentaroKoga** [camrbuss/pinci#7]
I'm beginner to raspberry pi keyboard so just worried if I can build and set it up properly without guide.
I have experience of building sweep and cantor but not raspberry pi.

I'm sorry if you already put a guide somewhere and I just didn't find it.

Thanks a lot for making this✨

**Comment by camrbuss** [comment]
I don't have a build guide as you just solder on the Raspberry Pi Pico, the one resistor (popl or popr), the 3.5mm jack, and then the switches.

Besides soldering the resistor and jack before everything else, there is no special order you need to follow.

I'm happy to answer questions if you decide to attempt the build. If you are new to diy electronics this might not be the best start, but it is certainly possible.

Thanks for the interest! 🦀

**Comment by KentaroKoga** [comment]
Thanks for your reply! I think I'll give it a try:)
